//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP.HCBBOOK.CORE.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerSubClient
    {
        public string MAC { get; set; }
        public string MacIdMaster { get; set; }
        public string NameComputer { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> DateJoin { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsDisable { get; set; }
    
        public virtual ComputerMasterClient ComputerMasterClient { get; set; }
    }
}
