//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP.HCBBOOK.CORE.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SGPCloudEntities : DbContext
    {
        public SGPCloudEntities()
            : base("name=SGPCloudEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRoles> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<ComputerMasterClient> ComputerMasterClient { get; set; }
        public virtual DbSet<ComputerSubClient> ComputerSubClient { get; set; }
        public virtual DbSet<HistoryLoginSession> HistoryLoginSession { get; set; }
        public virtual DbSet<Licence> Licence { get; set; }
        public virtual DbSet<List_Game_Disk> List_Game_Disk { get; set; }
        public virtual DbSet<Menu_Type> Menu_Type { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User_Control_Menu> User_Control_Menu { get; set; }
        public virtual DbSet<User_Game_Owner> User_Game_Owner { get; set; }
        public virtual DbSet<User_Licence> User_Licence { get; set; }
        public virtual DbSet<UserProfile> UserProfile { get; set; }
        public virtual DbSet<VersionHistory> VersionHistory { get; set; }
    }
}
