//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP.HCBBOOK.CORE.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryLoginSession
    {
        public string UserId { get; set; }
        public int Id { get; set; }
        public Nullable<System.DateTime> TimeStartLogin { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public string NameMachine { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
