//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP.HCBBOOK.CORE.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Licence()
        {
            this.User_Licence = new HashSet<User_Licence>();
        }
    
        public string Id { get; set; }
        public string LicenceKey { get; set; }
        public bool IsActive { get; set; }
        public int NumberDevicesLiveActive { get; set; }
        public int MaxNumberDevices { get; set; }
        public decimal Price { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string UserIdCreate { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Licence> User_Licence { get; set; }
    }
}
