//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP.HCBBOOK.CORE.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_Game_Disk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public List_Game_Disk()
        {
            this.User_Game_Owner = new HashSet<User_Game_Owner>();
        }
    
        public string Id { get; set; }
        public string NameGame { get; set; }
        public string URLExecute { get; set; }
        public string IconUrL { get; set; }
        public string IcoUrl { get; set; }
        public byte[] IconImage { get; set; }
        public Nullable<System.DateTime> DateScan { get; set; }
        public Nullable<double> Size { get; set; }
        public string Description { get; set; }
        public string Version { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsGameOnline { get; set; }
        public Nullable<bool> IsGameChienThuat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Game_Owner> User_Game_Owner { get; set; }
    }
}
