//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP.HCBBOOK.CORE.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Game_Owner
    {
        public string UserId { get; set; }
        public string GameId { get; set; }
        public bool IsShowOnMenu { get; set; }
        public bool IsRemoveOnDisk { get; set; }
        public Nullable<bool> IsGameHot { get; set; }
        public string URLDiskGame { get; set; }
        public string IconUrlCustom { get; set; }
        public string IcoUrlCustom { get; set; }
        public Nullable<int> SumNumberPlay { get; set; }
        public Nullable<int> NumberPlayInDay { get; set; }
    
        public virtual List_Game_Disk List_Game_Disk { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
