//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP.HCBBOOK.CORE.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Licence
    {
        public string Userid { get; set; }
        public string LicenceId { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsLive { get; set; }
        public Nullable<System.DateTime> DateInput { get; set; }
        public string MACMasterId { get; set; }
    
        public virtual ComputerMasterClient ComputerMasterClient { get; set; }
        public virtual Licence Licence { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
