//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP.HCBBOOK.CORE.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Control_Menu
    {
        public string UserId { get; set; }
        public string GameId { get; set; }
        public int MenuId { get; set; }
        public Nullable<bool> IsHidden { get; set; }
    
        public virtual Menu_Type Menu_Type { get; set; }
    }
}
