//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP.HCBBOOK.CORE.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VersionHistory
    {
        public int Id { get; set; }
        public string Version { get; set; }
        public Nullable<bool> IsUpdateAvailable { get; set; }
        public Nullable<bool> Mandatory { get; set; }
        public string InstallerArgs { get; set; }
        public string Checksum { get; set; }
        public string HashingAlgorithm { get; set; }
        public string SoftName { get; set; }
        public Nullable<System.DateTime> DateChange { get; set; }
        public string ChangeLog { get; set; }
    }
}
