//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP.HCBBOOK.GameMenu.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameItem
    {
        public string Id { get; set; }
        public string NameGame { get; set; }
        public string URLExecute { get; set; }
        public string IconUrL { get; set; }
        public string IcoUrL { get; set; }
        public byte[] IconImage { get; set; }
        public Nullable<System.DateTime> DateScan { get; set; }
        public Nullable<float> Size { get; set; }
        public string Description { get; set; }
        public string Version { get; set; }
        public bool IsGameOnline { get; set; }
        public bool IsGameHot { get; set; }
        public bool IsGameChienThuat { get; set; }
    }
}
